@startuml

skinparam linetype ortho
skinparam Monochrome true
skinparam classAttributeIconSize 0

title Communication Manager Sequence Diagram
actor Factory


Factory-> CommsManager: startServer
activate CommsManager
loop loop

end

Factory-> CommsManager: stopServer

deactivate CommsManager

@enduml