@startuml
skinparam linetype ortho
skinparam Monochrome true
skinparam classAttributeIconSize 0

title Database Manager Sequence Diagram

actor Factory as Factory
actor Manager as Manager

Factory -> DatabaseManager: initDatabase
activate DatabaseManager

DatabaseManager <- Manager: query

DatabaseManager <- Manager: update

Factory -> DatabaseManager: closeDatabase
deactivate DatabaseManager
@enduml