@startuml

actor Actor as Actor
actor Manager as Manager

Actor -> DatabaseManager: initDatabase
activate DatabaseManager

DatabaseManager <- Manager: query

DatabaseManager <- Manager: update

Actor -> DatabaseManager: closeDatabase
deactivate DatabaseManager
@enduml