@startuml

skinparam linetype ortho
skinparam Monochrome true
skinparam classAttributeIconSize 0

Actor Factory
Factory ->CommsManager: Load request
CommsManager->CommandManager: 

CommandManager->":CommandRequest": 

":CommandRequest"->DatabaseManager:update


Factory -> DatabaseManager : query(LoadOrder)
note left: query pending orders

Factory->RoutingManager:makeRoute 

alt success    
    Factory -> RoutingManager: initRoute()

    Factory -> DatabaseManager: update(LoadOrder)
end

@enduml