@startuml
skinparam linetype ortho
skinparam Monochrome true
skinparam classAttributeIconSize 0

title Order List Sequence Diagram
actor ERP as ERP

ERP -> CommsManager
CommsManager -> CommandManager

activate CommandManager

    CommandManager -> DatabaseManager : query(TransformationOrder)
    note left: get all transformation orders

    create CommandResponseOrderList
    CommandManager -> CommandResponseOrderList : create new response

    CommandManager -> CommsManager
    CommsManager -> ERP

deactivate CommandManager

@enduml 