@startuml
skinparam linetype ortho
skinparam Monochrome true
skinparam classAttributeIconSize 0

title Region Manager Sequence Diagram

actor Factory as Factory

Factory -> RegionManager: getPartRegion
activate RegionManager

loop all regions
    RegionManager -> ":Region": hasPart
   
    loop all region conveyors
        ":Region" -> ":Conveyor": hasPart

        alt true
            ":Conveyor" -> ":Region": return true
            ":Region" -> "RegionManager": return region
        end
    end
end

RegionManager -> Factory: return region
deactivate RegionManager

Factory -> RegionManager: getConveyorRegion
activate RegionManager

loop all regions
    RegionManager -> ":Region": hasConveyor
   
    alt true
        ":Region" -> "RegionManager": return region
    end
end

RegionManager -> Factory: return region
deactivate RegionManager
@enduml