@startuml
skinparam linetype ortho
skinparam Monochrome true
skinparam classAttributeIconSize 0

title Routing Manager Sequence Diagram

actor Factory as Factory

Factory -> RoutingManager: makeRoute
activate RoutingManager

RoutingManager -> RegionManager: getConveyorRegion
note left: origin conveyor region

RoutingManager -> RegionManager: getConveyorRegion
note left: dest conveyor region

RoutingManager -> RegionManager: getConnectedRegions

loop connected regions
    RoutingManager -> Region: getConveyors
    RoutingManager -> RoutingManager: makeRegionRoutes
end

RoutingManager -> RoutingManager: traceRoute

alt success
    create Route
    RoutingManager -> Route: new
    RoutingManager -> Factory: return route
else failed
    RoutingManager -> Factory: return NULL
end


deactivate RoutingManager

Factory -> RoutingManager: initRoute
activate RoutingManager
RoutingManager -> RoutingManager: enqueueRoute
RoutingManager -> Factory: return success
deactivate RoutingManager
@enduml