@startuml
skinparam linetype ortho
skinparam Monochrome true
skinparam classAttributeIconSize 0

title Storage Manager Sequence Diagram
actor actor 

actor->StorageManager: extract
activate StorageManager

StorageManager -> DatabaseManager: getQuantity
activate DatabaseManager
DatabaseManager -> StorageManager: return Quantity
deactivate DatabaseManager

alt PartNumber > 0
StorageManager -> DatabaseManager: update
activate DatabaseManager
DatabaseManager -> StorageManager: return true
deactivate DatabaseManager

StorageManager -> actor: return Extract
 

else else

    StorageManager -> actor: return failed
    deactivate StorageManager
    end


actor->StorageManager: store
activate StorageManager

StorageManager -> DatabaseManager: update
activate DatabaseManager
DatabaseManager -> StorageManager: return true
deactivate DatabaseManager

StorageManager -> actor: return store
deactivate StorageManager


@enduml