@startuml

skinparam linetype ortho
skinparam Monochrome true
skinparam classAttributeIconSize 0

title Unload Order Sequence Diagram
Actor Factory
Factory ->CommsManager: Load request
CommsManager->CommandManager: 

CommandManager->":CommandRequest": 

":CommandRequest"->DatabaseManager:update


Factory -> DatabaseManager : query(UnloadOrder)
note left: query pending orders

Factory->RoutingManager:makeRoute 

Factory->StorageManager: extract
alt success   
    Factory -> RoutingManager: initRoute()

    Factory -> DatabaseManager: update(UnloadOrder)
end

@enduml