@startuml
skinparam linetype ortho
skinparam Monochrome true

title Database UML


class Part{
	UUID id;
  int orderId;
  partState state;
}

Part --"1" PartType

class PartType {
  varchar name;
  enum defaultColor;
}

class TransformOrder{
  int orderID;
  date date;
  int quantity;
  int deadline;
  int penalty;
  int completed;
  time start_date;
  time finish_date;
  time received_date;
}

TransformOrder --"2" PartType

class UnloadOrder{
  int orderID;
	int conveyorId;
  date date;
  int quantity;
}

UnloadOrder --"1" PartType

class Process{
  int id;
  int assemblerId;
	time duration;
  EnumTool tool;
}

Process --"2" PartType

class ProcessLog{
  int id;
	int assemblerId;
	time duration;
}

ProcessLog --"1" Part
ProcessLog --"2" PartType

class UnloadingBayLog{
  int id;
	int conveyorId;
}

UnloadingBayLog --"1" Part
UnloadingBayLog --"1" PartType

@enduml